# Generated by Django 3.1.1 on 2020-12-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_title', models.CharField(default='', max_length=200)),
                ('note', models.CharField(default='', max_length=500)),
                ('add_date', models.DateField(default='')),
            ],
        ),
    ]
