# Generated by Django 3.1.1 on 2021-01-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_note_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_title_when_locked',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='note',
            name='note_when_locked',
            field=models.CharField(default='', max_length=500),
        ),
    ]
