# Generated by Django 3.1.1 on 2021-01-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210111_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_title', models.CharField(default='', max_length=200)),
                ('note', models.CharField(default='', max_length=500)),
                ('add_date', models.DateField(default='')),
                ('author', models.CharField(default='', max_length=200)),
                ('password', models.CharField(blank=True, default='', max_length=200)),
                ('note_title_when_locked', models.CharField(blank=True, default='', max_length=500)),
                ('note_when_locked', models.CharField(blank=True, default='', max_length=500)),
                ('label', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='note',
            name='note_title_when_locked',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_when_locked',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='note',
            name='password',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
