# Generated by Django 3.1.1 on 2021-01-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210117_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='note',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='label',
            name='note_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
