# Generated by Django 3.1.1 on 2021-01-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20210120_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='note_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
