# Generated by Django 3.1.1 on 2021-01-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_label_note_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='note_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
